### PR TITLE
Review memory/malloc errors and potential leaks.

### LINKED ISSUE #473: Refactor: Memory allocation errors
When a memory allocation fails such as `malloc` we log an error about this however the error is not standardized. It would probably make sense to standardize this error with a variable and use it everywhere.

Example:

```c
		char *result = (char *) malloc(length * sizeof(char));
		if (result == NULL)
		{
			log_error("Failed to allocate memory, probably because it's all used");
			return NULL;
		}
```

suggestion:

```c
#define ALLOCATION_FAILED_ERROR <a nice message>
...
		char *result = (char *) malloc(length * sizeof(char));
		if (result == NULL)
		{
			log_error(ALLOCATION_FAILED_ERROR);
			return NULL;
		}
```

### PR DESCRIPTION
**Pull request by DimCitus**
We avoid using malloc in most of the code base, and still require it when
reading a file from disk. Some places in the code didn't get the memo that
read_file() and read_file_if_exists() leak memory, and the caller needs to
call free().

Also, because we only have a handful of malloc() failed error messages, it's
a good thing to always use the same error message format. And this format
should not require memory allocation of course. I believe %m is okay with
that.

Fixes #473

### CODE REVIEW

File: src/bin/pg_autoctl/lock_utils.c [hunk 1]
```diff
@@ -194,14 +193,21 @@ semaphore_cleanup(const char *pidfile)
...
 		return false;
 	}
 
-	if (!stringToInt(semIdString, &(semaphore.semId)))
+	if (!stringToInt(fileLines[PIDFILE_LINE_SEM_ID], &(semaphore.semId)))
 	{
 		/* errors have already been logged */
+		free(fileContents);
 		return false;
 	}
```
Comment (JelteF) [inline src/bin/pg_autoctl/lock_utils.c:212]: I think you missed one here in the happy path:
```suggestion
	}
	free(fileContents);
```

File: src/bin/pg_autoctl/keeper.c [hunk 2]
```diff
@@ -927,8 +930,17 @@ keeper_ensure_configuration(Keeper *keeper, bool postgresNotRunningIsOk)
 			return false;
```
Comment (JelteF) [inline src/bin/pg_autoctl/keeper.c:930]: this error and the two above can leak `currentConfContents`

File: src/bin/pg_autoctl/pidfile.c [hunk 3]
```diff
@@ -332,11 +327,14 @@ read_service_pidfile_version_strings(const char *pidfile,
 		/* extension version string, comes later in the file */
 		if (pidLine == PIDFILE_LINE_EXTENSION_VERSION)
 		{
+			free(fileContents);
```
Comment (JelteF) [inline src/bin/pg_autoctl/pidfile.c:330]: This `free` should happen after the `strlcpy` in the line below.

**Review by JelteF — APPROVED** [review]
Looks good overall, left some small comments

File: src/bin/pg_autoctl/keeper.c [hunk 4]
```diff
@@ -927,8 +930,17 @@ keeper_ensure_configuration(Keeper *keeper, bool postgresNotRunningIsOk)
...
 		}
 
-		if (currentConfContents == NULL ||
-			strcmp(newConfContents, currentConfContents) != 0)
+		replicationSettingsHaveChanged =
+			currentConfContents == NULL ||
+			strcmp(newConfContents, currentConfContents) != 0;
+
+		if (currentConfContents != NULL)
```
[the remark this answers is not in the document]
Comment (DimCitus) [reply src/bin/pg_autoctl/keeper.c]: Thanks, fixed then!

File: src/bin/pg_autoctl/lock_utils.c [hunk 5]
```diff
@@ -194,14 +193,21 @@ semaphore_cleanup(const char *pidfile)
...
+				  "it contains %d lines, semaphore id is expected in line %d",
+				  pidfile,
+				  lineCount,
+				  PIDFILE_LINE_SEM_ID);
+		free(fileContents);
 		return false;
 	}
 
-	if (!stringToInt(semIdString, &(semaphore.semId)))
+	if (!stringToInt(fileLines[PIDFILE_LINE_SEM_ID], &(semaphore.semId)))
```
[the remark this answers is not in the document]
Comment (DimCitus) [reply src/bin/pg_autoctl/lock_utils.c:207]: Yeah, took me some time to figure out that more work needed to happen here than just the memory freeing...

File: src/bin/pg_autoctl/lock_utils.c (hunk 1 above)
Comment (DimCitus) [reply src/bin/pg_autoctl/lock_utils.c:212]: Done now, thanks.

File: src/bin/pg_autoctl/keeper.c (hunk 2 above)
Comment (DimCitus) [reply src/bin/pg_autoctl/keeper.c:933]: Good point, fixed.

File: src/bin/pg_autoctl/pidfile.c (hunk 3 above)
Comment (DimCitus) [reply src/bin/pg_autoctl/pidfile.c]: Good point, done too!
