### PR TITLE
Fix initialiazing an already existing Postgres cluster.

### LINKED ISSUE #111: Registering a pre-existing Postgres cluster to the monitor
I can add a stopped server, but if I try to add a server that is running and then I stop it, I can not add it after that.

```
[marco@localhost pgaf-state]$ pg_ctl -D node1 -l node1/logfile -w start -o "-p 6001"                                                                                               
waiting for server to start.... done
server started
[marco@localhost pgaf-state]$ pg_autoctl create postgres --pgdata node1 --pgport 6001 --monitor postgres://autoctl_node@localhost.localdomain:6000/pg_auto_failover --nodename localhost
14:17:13 INFO  Found pg_ctl for PostgreSQL 11.5 at /home/marco/pgsql-11/bin/pg_ctl
14:17:13 WARN  A postgres directory already exists at "/home/marco/citus/pg_auto_failover-master/pgaf-state/node1", registering as a single node
14:17:13 INFO  Registered node localhost:6001 with id 8 in formation "default", group 0, state "single"
14:17:13 INFO  Writing keeper state file at "/home/marco/.local/share/pg_autoctl/home/marco/citus/pg_auto_failover-master/pgaf-state/node1/pg_autoctl.state"
14:17:13 INFO  Writing keeper init state file at "/home/marco/.local/share/pg_autoctl/home/marco/citus/pg_auto_failover-master/pgaf-state/node1/pg_autoctl.init"
14:17:13 INFO  Successfully registered as "single" to the monitor.
14:17:13 INFO  FSM transition from "init" to "single": Start as a single node
14:17:13 INFO  Initialising postgres as a primary
14:17:13 ERROR PostgreSQL is already running at "node1", refusing to initialize a new cluster on-top of the current one.
14:17:13 ERROR Failed to transition from state "init" to state "single", see above.
[marco@localhost pgaf-state]$ pg_ctl -D node1 stop
waiting for server to shut down.... done
server stopped
[marco@localhost pgaf-state]$ pg_autoctl create postgres --pgdata node1 --pgport 6001 --monitor postgres://autoctl_node@localhost.localdomain:6000/pg_auto_failover --nodename localhost
14:17:19 INFO  Continuing from a previous `pg_autoctl create` failed attempt
14:17:19 INFO  PostgreSQL state at registration time was: PostgreSQL is running and a primary server
14:17:19 INFO  FSM transition from "init" to "single": Start as a single node
14:17:19 INFO  Initialising postgres as a primary
14:17:19 ERROR PostgreSQL is already running at "node1", refusing to initialize a new cluster on-top of the current one.
14:17:19 ERROR Failed to transition from state "init" to state "single", see above.
```

### PR DESCRIPTION
**Pull request by DimCitus**
We refuse to own an already running Postgres cluster. Then it's fair for us
to also accept that the user might just stop the Postgres instance and give
it to us again. This patch makes us recognize the situation and proceed with
our initialisation steps in that case.

Fixes #111.

### CODE REVIEW

File: src/bin/pg_autoctl/keeper.c [hunk 1]
```diff
@@ -892,6 +868,48 @@ keeper_init_state_write(Keeper *keeper)
...
+		initState->pgInitState = PRE_INIT_STATE_EXISTS;
+	}
+	else
+	{
+		initState->pgInitState = PRE_INIT_STATE_EMPTY;
+	}
+
+	return true;
+}
+
```
Comment (mtuncer) [inline src/bin/pg_autoctl/keeper.c]: missing empty line

File: src/bin/pg_autoctl/fsm_transition.c [hunk 2]
```diff
@@ -85,6 +85,26 @@ fsm_init_primary(Keeper *keeper)
...
+	 */
+	if (initState.pgInitState >= PRE_INIT_STATE_RUNNING)
+	{
+		if (!keeper_init_state_discover(keeper, &initState))
+		{
+			/* errors have already been logged */
+			return false;
+		}
+
+		if (initState.pgInitState < PRE_INIT_STATE_RUNNING)
```
Comment (mtuncer) [inline src/bin/pg_autoctl/fsm_transition.c]: may be one line comment on why pgInitState may have changed

File: src/bin/pg_autoctl/keeper.c (hunk 1 above)
Comment (DimCitus) [reply src/bin/pg_autoctl/keeper.c]: Fixed, thanks!

File: src/bin/pg_autoctl/fsm_transition.c (hunk 2 above)
Comment (DimCitus) [reply src/bin/pg_autoctl/fsm_transition.c]: Added, thanks!
