### PR TITLE
Fix/cli perform destroy

### LINKED ISSUE #94: Permissions missing in monitor database
Hi,

is this a known issue?

```
postgres@pg-af3:/home/postgres/ [af] pg_autoctl show state
Name |   Port | Group |  Node |     Current State |    Assigned State
---------------------------+--------+-------+-------+-------------------+------------------
pg-af1.it.dbi-services.com |   5432 |     0 |     1 |           primary |           primary
pg-af2.it.dbi-services.com |   5432 |     0 |     2 |         secondary |         secondary

17:29:11 postgres@pg-af3:/home/postgres/ [af] psql postgres://autoctl@pg-af3:5432/pg_auto_failover
psql (12.0 dbi services build)
Type "help" for help.

pg_auto_failover=> select pgautofailover.perform_failover(formation_id => 'default', group_id => 0);
ERROR:  permission denied for schema pgautofailover
LINE 1: select pgautofailover.perform_failover(formation_id => 'defa...
^
```

PostgreSQL 12 on CentOS 8.
pg_autoctl version 1.0.5

Not an issue to fix it manually but I still wonder why permissions are missing in the monitor database. Did I miss something?

Best regards
Daniel

### PR DESCRIPTION
**Pull request by DimCitus**
- Add `pg_autoctl perform failover` as a CLI operation
  - Add `pg_autoctl perform switchover` as a synonym to it: when done in a controlled way what we implement is actually a switch-over, thanks to the careful implementation of the FSM on the monitor and to the default to synchronous replication
  - Remove `pg_autoctl destroy` and make it an option to `pg_autoctl drop node --destroy` instead, that fits better with the spirit of our CLI
  - Re-order get/set commands so that they are listed with the command that have sub-commands, before the final commands

In passing, we fix #94 by making `pgautofailover.perform_failover()` a SECURITY DEFINER function.

### CODE REVIEW

File: src/bin/pg_autoctl/cli_create_drop_node.c [hunk 1]
```diff
@@ -614,73 +720,171 @@ cli_drop_node(int argc, char **argv)
...
+				 "state file \"%s\" does not exist",
+				 config.pathnames.state);
 	}
 
-	if (pg_ctl_stop(config.pgSetup.pg_ctl, config.pgSetup.pgdata))
+	/*
+	 * Either --destroy the whole Postgres cluster and configuraiton, or leave
+	 * enough behind us that it's possible to re-join a formation later.
+	 */
+	if (dropAndDestroy)
```
Comment (mtuncer) [inline src/bin/pg_autoctl/cli_create_drop_node.c]: destroy also includes drop right ? why don't be make this earlier in the function ? This way we might need less changes in the drop implementation

Comment (DimCitus) [reply src/bin/pg_autoctl/cli_create_drop_node.c]: Well the rest of the actions are common to both `drop node` and `drop node --destroy`, so we don't need the test until way down in the implementation. The new code is reading the configuration file to grab the `postgresql.pg_ctl` parameter and make sure that's the one we use, where before we would just use `set_first_pgctl` and might use `pg_ctl` from Postgres 12 on a Postgres 11 cluster.

File: src/bin/pg_autoctl/cli_create_drop_node.c [hunk 2]
```diff
@@ -33,19 +33,24 @@
 #include "primary_standby.h"
 
 MonitorConfig monitorOptions;
+bool dropAndDestroy = false;
```
Comment (mtuncer) [inline src/bin/pg_autoctl/cli_create_drop_node.c]: not a fun of global stuff. can we at least make it static ?

File: tests/test_create_run.py [hunk 3]
```diff
@@ -16,11 +16,11 @@ def teardown_module():
 
 def test_000_create_monitor():
     global monitor
-    monitor = cluster.create_monitor("/tmp/basic/monitor")
+    monitor = cluster.create_monitor("/tmp/create--run/monitor")
```
Comment (mtuncer) [inline tests/test_create_run.py]: maybe `create-run` or `create_run`

File: tests/pgautofailover_utils.py [hunk 4]
```diff
@@ -687,7 +687,7 @@ def stop(self):
 
             try:
                 pgid = os.getpgid(self.run_proc.pid)
-                os.killpg(pgid, signal.SIGTERM)
+                os.killpg(pgid, signal.SIGQUIT)
```
Comment (mtuncer) [inline tests/pgautofailover_utils.py]: Is this better than SIGTERM ? documentation says it is a signal to dump core

File: tests/test_create_run.py (hunk 3 above)
Comment (DimCitus) [reply tests/test_create_run.py]: Done using `create-run` ; I did like using `--run` in the name of the directory because we are testing `pg_autoctl create --run`, but yeah, that's a tad too much.

File: tests/pgautofailover_utils.py (hunk 4 above)
Comment (DimCitus) [reply tests/pgautofailover_utils.py]: We implement our own signal handlers in our code, see https://github.com/citusdata/pg_auto_failover/blob/master/src/bin/pg_autoctl/signals.c#L79 for the SIGQUIT handler. That's an _immediate shutdown_.

File: src/bin/pg_autoctl/cli_create_drop_node.c (hunk 2 above)
Comment (DimCitus) [reply src/bin/pg_autoctl/cli_create_drop_node.c]: Done, thanks!
