### PR TITLE
Per valgrind, fix some memory leaks.

### LINKED ISSUE #679: memory leak in process pg_autoctl: node active
memory leak in process pg_autoctl: node active
over 2 Gb RES by one day!

### PR DESCRIPTION
**Pull request by DimCitus**
We would be using PQfreemem on a PQExpBuffer, where it's expected to be
using destroyPQExpBuffer instead.

Also we were short of a call to finish the
connection to the monitor notification client when exiting from the service
keeper process, although adding this clean-up doesn't seem to impact the
valgrind reports.

Fixes #679 (again).

### CODE REVIEW

File: src/bin/pg_autoctl/pgsql.c [hunk 1]
```diff
@@ -1640,8 +1640,8 @@ pgsql_replication_slot_create_and_drop(PGSQL *pgsql, NodeAddressArray *nodeArray
 	if (!BuildNodesArrayValues(nodeArray, &sqlParams, values))
 	{
 		/* errors have already been logged */
-		PQfreemem(query);
-		PQfreemem(values);
+		destroyPQExpBuffer(query);
+		destroyPQExpBuffer(values);
```
Comment (JelteF) [inline src/bin/pg_autoctl/pgsql.c:1644]: This same issue seems to be present in the function `pgsql_replication_slot_maintain`

**Review by JelteF — CHANGES_REQUESTED** [review]

File: src/bin/pg_autoctl/pgsql.c (hunk 1 above)
Comment (DimCitus) [reply src/bin/pg_autoctl/pgsql.c:1644]: Fixed now. Curiously didn't appear in the valgrind report.

**Review by JelteF — APPROVED** [review]
