### PR TITLE
Deduplicate PATH entries that are symlinks resolving to other PATH entries

### LINKED ISSUE #545: Install Failure -- Ubuntu 20.04 + pg_auto_failover 1.4
I'm not sure what's up, but on brand new Ubuntu 20.04 installations the install does not seem to work.

Installation of packages goes fine:
```
kelliott@af-db-controller:~$ sudo apt-get install postgresql-11-auto-failover
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'postgresql-11-auto-failover-1.4' instead of 'postgresql-11-auto-failover'
The following additional packages will be installed:
  pg-auto-failover-cli-1.4 postgresql-11
The following NEW packages will be installed:
  pg-auto-failover-cli-1.4 postgresql-11 postgresql-11-auto-failover-1.4
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/14.8 MB of archives.
After this operation, 48.3 MB of additional disk space will be used.
Do you want to continue? [Y/n]
Preconfiguring packages ...
Selecting previously unselected package pg-auto-failover-cli-1.4.
(Reading database ... 108711 files and directories currently installed.)
Preparing to unpack .../pg-auto-failover-cli-1.4_1.4.1-1_amd64.deb ...
Unpacking pg-auto-failover-cli-1.4 (1.4.1-1) ...
Selecting previously unselected package postgresql-11.
Preparing to unpack .../postgresql-11_11.10-1.pgdg20.04+1_amd64.deb ...
Unpacking postgresql-11 (11.10-1.pgdg20.04+1) ...
Selecting previously unselected package postgresql-11-auto-failover-1.4.
Preparing to unpack .../postgresql-11-auto-failover-1.4_1.4.1-1_amd64.deb ...
Unpacking postgresql-11-auto-failover-1.4 (1.4.1-1) ...
Setting up postgresql-11 (11.10-1.pgdg20.04+1) ...
update-alternatives: using /usr/share/postgresql/11/man/man1/postmaster.1.gz to provide /usr/share/man/man1/postmaster.1.gz (postmaster.1.gz) in auto mode
Setting up pg-auto-failover-cli-1.4 (1.4.1-1) ...
Setting up postgresql-11-auto-failover-1.4 (1.4.1-1) ...
Processing triggers for postgresql-common (223.pgdg20.04+1) ...
Building PostgreSQL dictionaries from installed myspell/hunspell packages...
Removing obsolete dictionary files:
Processing triggers for man-db (2.9.1-1) ...
```

The version installed:
```
kelliott@af-db-controller:~$ /usr/bin/pg_autoctl --version
pg_autoctl version 1.4.1
pg_autoctl extension version 1.4
compiled with PostgreSQL 13.1 (Ubuntu 13.1-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
compatible with Postgres 10, 11, 12, and 13
```

Then on to setting up the monitor:
```
kelliott@af-db-controller:~$ export PGDATA=./monitor
kelliott@af-db-controller:~$ export PGPORT=5000
kelliott@af-db-controller:~$ pg_autoctl create monitor --ssl-self-signed --hostname 10.90.31.20 --auth trust --run
22:42:46 55434 INFO  Using default --ssl-mode "require"
22:42:46 55434 INFO  Using --ssl-self-signed: pg_autoctl will create self-signed certificates, allowing for encrypted network traffic
22:42:46 55434 WARN  Self-signed certificates provide protection against eavesdropping; this setup does NOT protect against Man-In-The-Middle attacks nor Impersonation attacks.
22:42:46 55434 WARN  See https://www.postgresql.org/docs/current/libpq-ssl.html for details
22:42:46 55434 WARN  Failed to find pg_ctl command in your PATH
22:42:46 55434 INFO  Found more than one pg_config entry in current PATH:
22:42:46 55434 INFO  Found "/usr/bin/pg_config" for pg version 13.1
22:42:46 55434 INFO  Found "/bin/pg_config" for pg version 13.1
22:42:46 55434 INFO  HINT: export PG_CONFIG to a specific pg_config entry
```

But then the monitor doesn't seem set up:
```
kelliott@af-db-controller:~$ pg_autoctl show uri --monitor --pgdata ./monitor
22:42:52 55445 ERROR Failed to open file "/home/kelliott/.config/pg_autoctl/home/kelliott/monitor/pg_autoctl.cfg": No such file or directory
22:42:52 55445 FATAL Failed to parse configuration file "/home/kelliott/.config/pg_autoctl/home/kelliott/monitor/pg_autoctl.cfg"
```

### PR DESCRIPTION
**Pull request by DimCitus**
In recent debian releases /bin is a symlink to /usr/bin, which means we're
going to find pg_config twice on that system. But it's twice the same entry,
and we can deduplicate and realize we only have one entry actually.

Fixes #545

### CODE REVIEW

File: src/bin/pg_autoctl/file_utils.c [hunk 1]
```diff
@@ -592,6 +592,73 @@ search_path(const char *filename, SearchPath *result)
...
+		{
+			log_error("Failed to normalize file name \"%s\": %m", currentPath);
+			return false;
+		}
+
+		/* add-in the realpath to dedup, unless it's already in there */
+		if (dedup->found == 0)
+		{
+			alreadyThere = false;
+		}
```
Comment (JelteF) [inline src/bin/pg_autoctl/file_utils.c:637]: No need to put this special case here afaict it all works fine with 0 (`for` loop is never entered).

File: src/bin/pg_autoctl/file_utils.c [hunk 2]
```diff
@@ -592,6 +592,73 @@ search_path(const char *filename, SearchPath *result)
...
+ */
+bool
+search_path_deduplicate_symlinks(SearchPath *results, SearchPath *dedup)
+{
+	if (results->found < 2)
+	{
+		/* copy our results over to dedup and be done already */
+		*dedup = *results;
+		return true;
+	}
```
Comment (JelteF) [inline src/bin/pg_autoctl/file_utils.c:615]: I think it's nicer to remove this to get consistent behaviour. This way we'll always have the `realpath` of the binary in the output.

File: src/bin/pg_autoctl/pgctl.c [hunk 3]
```diff
@@ -448,7 +456,16 @@ config_find_pg_ctl(PostgresSetup *pgSetup)
...
+			log_debug("Failed to find pg_ctl in PATH, looking for pg_config");
+		}
+		else
+		{
+			log_debug("Found %d entries for pg_ctl in PATH, "
+					  "looking for pg_config",
+					  pg_ctls.found);
+		}
 
 		if (set_pg_ctl_from_pg_config(&pgSetupFromPgConfig))
```
Comment (JelteF) [inline src/bin/pg_autoctl/pgctl.c:470]: I would expect that `set_pg_ctl_from_pg_config` would also use `search_path_deduplicate_symlinks`, but I don't see it in the diff.

**Review by JelteF — CHANGES_REQUESTED** [review]

File: src/bin/pg_autoctl/file_utils.c (hunk 1 above)
Comment (DimCitus) [reply src/bin/pg_autoctl/file_utils.c:637]: Ah yes. I didn't write the code like this on the first attempt, and it shows... good point.

Comment (DimCitus) [reply src/bin/pg_autoctl/file_utils.c]: Done now.

File: src/bin/pg_autoctl/file_utils.c (hunk 2 above)
Comment (DimCitus) [reply src/bin/pg_autoctl/file_utils.c]: Good point, done that way now.

File: src/bin/pg_autoctl/pgctl.c (hunk 3 above)
Comment (DimCitus) [reply src/bin/pg_autoctl/pgctl.c:478]: Added now, good point.

**Comment by JelteF** [comment]
There's this warning in travis:
```
/file_utils.Po -o file_utils.o file_utils.c

In file included from /usr/include/stdlib.h:1020:0,

                 from /usr/include/postgresql/10/server/c.h:82,

                 from /usr/include/postgresql/10/server/postgres_fe.h:25,

                 from file_utils.c:18:

In function ‘realpath’,

    inlined from ‘search_path_deduplicate_symlinks’ at file_utils.c:620:7:

/usr/include/x86_64-linux-gnu/bits/stdlib.h:43:9: warning: call to ‘__realpath_chk_warn’ declared with attribute warning: second argument of realpath must be either NULL or at least PATH_MAX bytes long buffer

  return __realpath_chk_warn (__name, __resolved, __bos (__resolved));

         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Also, all of the tests are failing (possibly because of the same thing).

**Comment by DimCitus** [comment]
> There's this warning in travis:

Ah yeah, `realpath` requires `PATH_MAX`. Fixed now, thanks for pointing it to me!

**Review by JelteF — APPROVED** [review]
