### PR TITLE
Fix how many nodes need to report their LSN to perform a failover.

### LINKED ISSUE #682: Node is promoted to wait_primary incorrectly
```
make cluster -j20 TMUX_LAYOUT=tiled NODES=3
```
1. wait until stable
2. Ctrl+C primary
3. Ctrl+C one secondary
4. Wait 1 minute, the other secondary is now wait_primary. 

This is incorrect, because with `number-sync-standbys = 1` we need to have 2 out of 3 nodes in the election to avoid losing commited data.

### PR DESCRIPTION
**Pull request by DimCitus**
With this patch we make sure that all the nodes that participage in the
quorum have reported their LSN before we select a candidate for failover.
Otherwise, we might lose committed data.

Fixes #682

### CODE REVIEW

File: src/monitor/group_state_machine.c [hunk 1]
```diff
@@ -1377,6 +1377,25 @@ BuildCandidateList(List *nodesGroupList, CandidateList *candidateList)
...
+			 * Otherwise, we didn't get its LSN and this node might be the most
+			 * advanced LSN. Picking it now might lead to loosing commited data
+			 * that was reported to the client connection.
+			 *
+			 * Only the nodes that participate in the quorum are required to
+			 * report their LSN, because only those nodes are waited by
+			 * Postgres to report a commit to the client connection.
+			 */
+			if (node->replicationQuorum &&
+				node->reportedState != REPLICATION_STATE_REPORT_LSN)
```
Comment (JelteF) [inline src/monitor/group_state_machine.c:1394]: What happens when the node is down and is in REPORT_LSN, but also had the highest LSN?

**Review by JelteF — CHANGES_REQUESTED** [review]
Looks like a reasonable change to fix this issue, but definitly needs a test.

File: src/monitor/group_state_machine.c (hunk 1 above)
Comment (DimCitus) [reply src/monitor/group_state_machine.c:1394]: First, it might not be the only node with the highest LSN, so the code path continues to see about that later in `SelectFailoverCandidateNode`. Second, if it's the highest LSN, we can still select another candidate and go through the fast forward state. Well at some point if that node is the only one with the highest LSN it needs to be back online to ensure success of the failover, I think.

**Comment by DimCitus** [comment]
> Looks like a reasonable change to fix this issue, but definitly needs a test.

The new test from #706 seems to cover the situation here, and also had to be adjusted to the new situation. I think we're good in terms of test coverage.

**Review by JelteF — APPROVED** [review]

File: tests/test_multi_alternate_primary_failures.py [hunk 2]
```diff
@@ -96,15 +96,14 @@ def test_003_002_stop_primary():
     assert node2.get_state().assigned == "primary"
     node2.fail()
 
-    # wait for node3 to become the new write node
-    assert node2.wait_until_assigned_state(target_state="demoted")
-    assert node3.wait_until_state(target_state="wait_primary")
+    # node3 can't be promoted when it's the only one reporting its LSN
+    assert node2.wait_until_assigned_state(target_state="draining")
+    assert node3.wait_until_state(target_state="report_lsn")
```
Comment (JelteF) [inline tests/test_multi_alternate_primary_failures.py:101]: I think it might be nice if we could wait a bit here, to ensure that `node3` doesn't become `wait_primary`.

Comment (JelteF) [reply tests/test_multi_alternate_primary_failures.py:101]: Something like:
```suggestion
    assert node3.wait_until_state(target_state="report_lsn")
    node3.sleep(10)
    assert node3.wait_until_state(target_state="report_lsn")
```

**Comment by DimCitus** [comment]
I have now revised this PR to implement some quorum validation when selecting a new node during a failover. Your comment that we might failover to a node that's alone and then have to block writes anyway, compared to having a read-only service, that's what I considered when working on this PR. Also note that previous to those changes, the failover mechanism when given a single node in REPORT_LSN would drive it to WAIT_PRIMARY, where writes are accepted and not replicated, contrary to the number_sync_standby setting when that's non-zero.

``` c
	/*
	 * So all the expected candidates did report their LSN, no node is missing.
	 * Let's see about selecting a candidate for failover now, when we do have
	 * candidates.
	 *
	 * To start the selection process, we require at least number_sync_standbys
	 * nodes to have reported their LSN and be currently healthy, otherwise we
	 * won't be able to maintain our guarantees: we would end-up with a node in
	 * WAIT_PRIMARY state with all the writes blocked for lack of standby
	 * nodes.
	 */
	char *formationId = activeNode->formationId;
	AutoFailoverFormation *formation = GetFormation(formationId);
	int minCandidates = formation->number_sync_standbys + 1;

	/* no candidates is a hard pass */
	if (candidateList.candidateCount == 0)
	{
		return false;
	}

	/* not enough candidates to promote and then accept writes, pass */
	else if (candidateList.candidateCount < minCandidates)
	{
		char message[BUFSIZE] = { 0 };

		LogAndNotifyMessage(
			message, BUFSIZE,
			"Failover still in progress with %d candidates having reported "
			"their LSN: %d nodes are required in the quorum to satisfy "
			"number_sync_standbys = %d in formation \"%s\", "
			"activeNode is " NODE_FORMAT
			" and reported state \"%s\"",
			candidateList.candidateCount,
			minCandidates,
			formation->number_sync_standbys,
			formation->formationId,
			NODE_FORMAT_ARGS(activeNode),
			ReplicationStateGetName(activeNode->reportedState));

		return false;
	}

	/* enough candidates to promote and then accept writes, let's do it! */
	else
	{
```

File: tests/test_multi_async.py [hunk 3]
```diff
@@ -256,31 +260,39 @@ def test_014_003_restart_node1():
...
+#   demoted      wait_primary secondary
+#                <down>
+#   demoted      demoted      report_lsn
+#                <up>
+#   demoted      wait_primary secondary
+#   <up>
+#   secondary    primary      secondary
+#
+#   ~~~
+#
```
Comment (JelteF) [inline tests/test_multi_async.py:295]: I think this new order should be instead of the one below

File: src/monitor/group_state_machine.c [hunk 4]
```diff
@@ -1256,8 +1256,47 @@ ProceedGroupStateForMSFailover(AutoFailoverNode *activeNode,
...
+	int minCandidates = formation->number_sync_standbys + 1;
+
+	/* no candidates is a hard pass */
+	if (candidateList.candidateCount == 0)
+	{
+		return false;
+	}
+
+	/* not enough candidates to promote and then accept writes, pass */
+	else if (candidateList.candidateCount < minCandidates)
```
Comment (JelteF) [inline src/monitor/group_state_machine.c:1277]: Should only use the count of the sync candidates here.

**Review by JelteF — CHANGES_REQUESTED** [review]
(see other comment)

File: tests/test_multi_async.py (hunk 3 above)
Comment (DimCitus) [reply tests/test_multi_async.py]: Thanks, that was a leftover that should have been cleaned-up. Done now.

File: src/monitor/group_state_machine.c (hunk 4 above)
Comment (DimCitus) [reply src/monitor/group_state_machine.c]: That's a good point. Done now.

File: src/monitor/group_state_machine.c [hunk 5]
```diff
@@ -1256,8 +1263,45 @@ ProceedGroupStateForMSFailover(AutoFailoverNode *activeNode,
...
+	}
+
+	/* not enough candidates to promote and then accept writes, pass */
+	else if (candidateList.quorumCandidateCount < minCandidates)
+	{
+		char message[BUFSIZE] = { 0 };
+
+		LogAndNotifyMessage(
+			message, BUFSIZE,
+			"Failover still in progress with %d candidates having reported "
```
Comment (JelteF) [inline src/monitor/group_state_machine.c:1288]: Let's make this error message a bit more explicit to avoid confusion:

```suggestion
			"Failover still in progress with %d candidates that participate in the quorum having reported "
```

Comment (DimCitus) [reply src/monitor/group_state_machine.c]: Thanks, added.

**Review by JelteF — APPROVED** [review]
