### PR TITLE
Fix IP address inquiries when ifa_addr is NULL.

### LINKED ISSUE #40: about the func findHostnameLocalAddress addr protocol judgment
ifa_addr is empty in the pptp protocol,"ifaddr->ifa_addr->sa_family == AF_INET" causes a segmentation fault.
Screenshot from 2019-07-09 16-26-56
Screenshot from 2019-07-09 16-10-05

### PR DESCRIPTION
**Pull request by DimCitus**
When using PPTP protocol some interfaces are exposed without an if_addr
field at all, which would trip our IP address discovery code and cause a
segfault.

Fixes #40.

### CODE REVIEW

File: src/bin/pg_autoctl/ipaddr.c [hunk 1]
```diff
@@ -133,6 +133,19 @@ fetchLocalCIDR(const char *localIpAddress, char *localCIDR, int size)
 		char netmask[INET6_ADDRSTRLEN] = { 0 };
 		char address[INET6_ADDRSTRLEN] = { 0 };
 
+		/*
+		 * Some interfaces might have an empty ifa_addr, such as when using the
```
Comment (mtuncer) [inline src/bin/pg_autoctl/ipaddr.c]: is there a way to test this ?

Comment (DimCitus) [reply src/bin/pg_autoctl/ipaddr.c]: It sounds complex to build a test case for this and easy enough a code path to accept it without tests? better continue the look than crashing (segfault) on a NULL value anyway...
