### PR TITLE
Adjust formation->number_sync_standbys when dropping a node.

### LINKED ISSUE #404: set_formation_number_sync_standbys seems too restrictive
I wonder whether some of these errors are necessary, especially when the value is 0:
```sql
pg_auto_failover=# SELECT set_formation_number_sync_standbys('default', 0);
ERROR:  Couldn't find the primary node in formation "default", group 0

pg_auto_failover=# SELECT pgautofailover.set_formation_number_sync_standbys('default', 0);
ERROR:  cannot set number_sync_standbys when current goal state for primary node 4 (172.23.156.186:6001) is "single", and current reported state is "single"
DETAIL:  The primary node so must be in state "primary" to be able to apply configuration changes to its synchronous_standby_names setting

pg_auto_failover=# SELECT pgautofailover.set_formation_number_sync_standbys('default', 0);
ERROR:  cannot set number_sync_standbys when current goal state for primary node 4 (172.23.156.186:6001) is "wait_primary", and current reported state is "wait_primary"
DETAIL:  The primary node so must be in state "primary" to be able to apply configuration changes to its synchronous_standby_names setting
```

I wanted to use it after reducing a multiple standby cluster to single, since I ended up with a single-node cluster that had number_sync_standbys 1.

### PR DESCRIPTION
**Pull request by DimCitus**
Fixes #404.

### CODE REVIEW

File: src/monitor/node_active_protocol.c [hunk 1]
```diff
@@ -1060,6 +1065,47 @@ RemoveNode(AutoFailoverNode *currentNode)
...
+	 * otherNodesGroupList is the list of all the remaining nodes, and that
+	 * includes the current primary, which might be setup with replication
+	 * quorum set to true (and probably is).
+	 */
+	countSyncStandbys = CountSyncStandbys(otherNodesGroupList) - 1;
+
+	LogAndNotifyMessage(message, BUFSIZE,
+						"CountSyncStandbys: %d", countSyncStandbys);
+
+	if (countSyncStandbys < (formation->number_sync_standbys + 1))
```
Comment (onderkalaci) [inline src/monitor/node_active_protocol.c:1080]: Is otherwise ever possible? I mean `countSyncStandbys  >= formation->number_sync_standbys + 1`?

We normally prevent it, still being defensive here is good, just want to ask in case I oversee some cases.

**Review by onderkalaci — APPROVED** [review]
This all makes sense, I've tried different scenarios with drop node all works as expected.

File: src/monitor/pgautofailover.sql [hunk 2]
```diff
@@ -741,49 +741,6 @@ grant execute on function
...
-  end if;
-
-  return old;
-end
-$$;
-
-comment on function pgautofailover.adjust_number_sync_standbys()
-        is 'adjust formation number_sync_standbys when removing a node, if needed';
-
-CREATE TRIGGER adjust_number_sync_standbys
```
[the remark this answers is not in the document]
Comment (DimCitus) [reply src/monitor/pgautofailover.sql:780]: Yes. I will update https://github.com/citusdata/pg_auto_failover/pull/386 as soon as this one is merged in master's branch.

File: src/monitor/node_active_protocol.c (hunk 1 above)
Comment (DimCitus) [reply src/monitor/node_active_protocol.c:1080]: That's the code that runs when we just dropped a standby. So it might be that we had two standby nodes and number_sync_standbys set to 1, all good. One standby removed. One standby left, number_sync_standbys now must be set to zero. That's what this test is all about.

Now, it could be that we had three standby nodes, and still had number_sync_standbys set to 1. Now a standby is removed. Two standby left, number_sync_standbys = 1, it's all good. That's your “otherwise” example, right?
