### PR TITLE
Avoid re-electing primary during a switchover.

### LINKED ISSUE #770: pg_autoctl perform switchover doesn't actually fail over since 1.6.1
### To reproduce
```
make cluster -j20 TMUX_LAYOUT=tiled NODES=3
pg_autoctl perform switchover
```

### What happens
Election happens and `node1` becomes primary again.

### PR DESCRIPTION
**Pull request by DimCitus**
When all the nodes are up and running, including the primary, a switchover
has a great chance of finding that the current primary is then the best
candidate to with the primary election, making the operation a no-op.

In this PR we tweak the current primary node's candidate priority in a way
that should make it lose the election, and reset the priority when the
election is over.

Fixes #770.

### CODE REVIEW

**Comment by JelteF** [comment]
Needs a test

File: src/monitor/node_active_protocol.c [hunk 1]
```diff
@@ -1394,6 +1394,32 @@ perform_failover(PG_FUNCTION_ARGS)
 
 		SetNodeGoalState(primaryNode, REPLICATION_STATE_DRAINING, message);
 
+		/*
+		 * When a failover is performed with all the nodes up and running, the
+		 * old primary is often in the best situation to win the election. In
+		 * that case, we trick the candidate priority in a way that makes the
+		 * node lose the election.
```
Comment (JelteF) [inline src/monitor/node_active_protocol.c:1401]:
```suggestion
		 * node lose the election. We undo this change in priority once the election completes.
```

Comment (DimCitus) [reply src/monitor/node_active_protocol.c:1401]: Done now, thanks.

**Comment by DimCitus** [comment]
> Needs a test

I tweaked an existing test to have the current primary and the target primary set to the same candidate priority, making sure that we still promote the target node rather than re-elect the current primary.

**Review by JelteF — APPROVED** [review]
