### PR TITLE
Refrain from useless verifications of pg_controldata properties.

### LINKED ISSUE #341: How to trigger failover with harsh errors?
I was playing with `pg_auto_failoverr` to trigger auto-failover, and decided to aggressively mark the data folder of the primary as  `read-only` via `chmod`.  As expected, Postgres started to fail with `2020-07-24 11:58:49.099 CEST [49153] FATAL:  could not open file "global/pg_filenode.map": Permission denied` type of errors.

After Postgres fails, I would have expected the `pg_auto_failover` to trigger a fail-over, but it didn't. I'm asking this as a question, is this expected to trigger a failover?

Steps to repro:

start up 1 primary +  1 standbys
```
pg_autoctl create monitor --pgport 10000 --pgdata /Users/onderkalaci/Documents/pg_auto_failover/monitor  --auth trust --ssl-self-signed --run

pg_autoctl create postgres --pgport 10001 --pgdata /Users/onderkalaci/Documents/pg_auto_failover/worker1a --auth trust --monitor postgres://autoctl_node@192.168.2.2:10000/pg_auto_failover?sslmode=require --pgctl /Users/onderkalaci/Documents/citus_code/pgenv/pgsql/bin//pg_ctl  --ssl-self-signed --run 

pg_autoctl create postgres --pgport 10002 --pgdata /Users/onderkalaci/Documents/pg_auto_failover/worker1b --auth trust --monitor postgres://autoctl_node@192.168.2.2:10000/pg_auto_failover?sslmode=require --pgctl /Users/onderkalaci/Documents/citus_code/pgenv/pgsql/bin//pg_ctl  --ssl-self-signed --run 


```

everything looks fine
```
pg_autoctl show state --pgdata /Users/onderkalaci/Documents/pg_auto_failover/monitor/
                                    Name |   Port | Group |  Node |     Current State |    Assigned State
-----------------------------------------+--------+-------+-------+-------------------+------------------
cusred034c9409-vl2.network.microsoft.com |  10001 |     0 |     1 |           primary |           primary
cusred034c9409-vl2.network.microsoft.com |  10002 |     0 |     2 |         secondary |         secondary
```

Mark everything read-only
```
cd /Users/onderkalaci/Documents/pg_auto_failover/worker1a
chmod -R 0444 *
```

The primary keeper continuous logs:
```
...
11:54:40 44827 ERROR Failed to check if file "/Users/onderkalaci/Documents/pg_auto_failover/worker1a/global/pg_control" exists: Permission denied
....
```

And, the states stall at
```
pg_autoctl show state --pgdata /Users/onderkalaci/Documents/pg_auto_failover/monitor/
                                    Name |   Port | Group |  Node |     Current State |    Assigned State
-----------------------------------------+--------+-------+-------+-------------------+------------------
cusred034c9409-vl2.network.microsoft.com |  10001 |     0 |     1 |           primary |    demote_timeout
cusred034c9409-vl2.network.microsoft.com |  10002 |     0 |     2 |  stop_replication |  stop_replication

```

### PR DESCRIPTION
**Pull request by DimCitus**
We don't need to check all our Postgres cluster invariants when Postgres is
not running. We're going to check for those as soon as Postgres is running
again anyway.

As seen in #341 too many checks for our invariants may block progress in the
FSM on the client side in edge cases.

### CODE REVIEW

**Comment by DimCitus** [comment]
> This unfortunately doesn't solve the issue as the issue is rooted `service_postgres_ctl_loop`.

I think this PR still would be good to merge even if it does not solve the specific issue we're trying to debug to begin with. We are still doing `pg_controldata` at times where this brings no practical information for driving the FSM (e.g. when in MAINTENANCE), We get more interesting information when we try to start Postgres again later, after all.

File: src/bin/pg_autoctl/keeper.c [hunk 1]
```diff
@@ -577,6 +546,65 @@ keeper_update_pg_state(Keeper *keeper)
...
+	if (keeperState->catalog_version_no != control->catalog_version_no &&
+		keeperState->catalog_version_no != 0)
+	{
+		/* Postgres major upgrade happened */
+		log_warn("PostgreSQL catalog version changed from %u to %u",
+				 keeperState->catalog_version_no,
+				 control->catalog_version_no);
+	}
+
+	keeperState->pg_control_version = control->pg_control_version;
```
Comment (onderkalaci) [inline src/bin/pg_autoctl/keeper.c:600]: I'd still move these 3  lines out of the function like before as  the name of the function is `keeper_state_check_postgres `  ( e.g., setting these values seem like an unexpected side effect from a function name `*check*`)

Or (less preferable), rename it to something like `keeper_state_check_and_set_postgres`

Comment (DimCitus) [reply src/bin/pg_autoctl/keeper.c]: Good point, done now.
